name: assignment_4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.16.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.11.0
  http: ^1.2.2
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
